name: Publish Docs

on:
  push:
    branches: [ docs ]

  # Run this workflow manually from Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  publish-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Checkout docs
        uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.DEPLOY_DOCS_DEV_KEY}}
          ref: docs

      # Install dependencies (mkdocs)
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Build the MkDocs site
        run: |
          source env/bin/activate
          mkdocs build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.DEPLOY_DOCS_DEV_KEY}}
          branch: gh-pages
          folder: site 
